# Generated by Django 5.1.4 on 2024-12-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.RemoveField(
            model_name='event',
            name='terms',
        ),
        migrations.AddField(
            model_name='event',
            name='term',
            field=models.CharField(choices=[('Güz', 'Güz'), ('Bahar', 'Bahar')], default='Güz', max_length=10),
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
