# Generated by Django 5.1.4 on 2024-12-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Mod', 'Mod'), ('User', 'User')], default='User', max_length=20),
        ),
    ]
