# Generated by Django 5.1.4 on 2024-12-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_blog_photo_url_blog_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='photo',
        ),
        migrations.AddField(
            model_name='blog',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
