# Generated by Django 5.1.4 on 2024-12-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_blog_photo_blog_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
