# Generated by Django 5.1.4 on 2024-12-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_blog_photo_url_blog_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='user_id',
        ),
    ]
