# Generated by Django 5.1.4 on 2024-12-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_blog_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category',
            new_name='category_id',
        ),
    ]
