# Generated by Django 5.1.4 on 2024-12-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_category_blog_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category_id',
            new_name='category',
        ),
    ]
