# Generated by Django 5.1.4 on 2024-12-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_category_id_blog_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
