# Generated by Django 5.1.4 on 2024-12-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_user_comment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='blog_id',
        ),
    ]
